### ISSUE TITLE
fix null pointer exception

### ISSUE THREAD

**Issue by mgalster** [veracitylab/provenance-demonstrator-movie#4]
Fix null pointer exception that occurred when requesting explanation of recommendation:
java.lang.NullPointerException: null
        at java.base/java.util.Objects.requireNonNull(Objects.java:221) ~[na:na]
        at java.base/java.util.Optional.<init>(Optional.java:107) ~[na:na]
        at java.base/java.util.Optional.of(Optional.java:120) ~[na:na]
        at nz.ac.canterbury.dataprovenancedemo.services.RecommendationService.getProvenanceData(RecommendationService.java:52) ~[main/:na]
        at nz.ac.canterbury.dataprovenancedemo.controllers.LibraryController.provenanceHandler(LibraryController.java:141) ~[main/:na]

**Comment by Matrixuniverses** [comment]
Fixed in 1429871
